[package]
name = "spindle"
version = "0.1.0"
edition = "2024"

[dependencies]
arena={path= "../../common/arena" }
heapless={path="../../submodules/heapless"}
log = "0.4.29"
unsized-builder = {path="../../common/unsized-builder"}

[dev-dependencies]
itertools = "0.14.0"
tokio = {version = "1.49.0",features = ["macros","rt"]}
rand_xorshift = "0.5.0"
rand = "0.10.0"
