[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "./runner.sh"
rustflags = [
#    "--cfg", "no_global_oom_handling",
    '--cfg=getrandom_backend="custom"',
]

[target.'cfg(all(target_arch = "riscv32", target_os = "none"))']
runner = "./runner.sh"
rustflags = [
#    "--cfg", "no_global_oom_handling",
    '--cfg=getrandom_backend="custom"',
]


[build]
target = "thumbv8m.main-none-eabihf"
#target = "riscv32i-unknown-none-elf"

[env]
DEFMT_LOG = "trace"

[unstable]
build-std = [ "core", "compiler_builtins", "alloc" ]
