[package]
name = "crypto-verifier"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-tls = {path="../../submodules/embedded-tls",default-features = false}
p256={version="0.13.2",default-features = false}
log = "0.4.29"
sha2={version="0.10.9",default-features = false}


[dev-dependencies]
tokio = {version="1.48.0",features = ["rt","macros","net"]}
rand_core = "0.6.4"
rand = "0.8.5"
embedded-io-adapters = {version="0.7.0",features = ["tokio-1"]}
embedded-io-async = "0.7.0"
simple_logger = "5.1.0"
hex-literal = "1.1.0"
