[package]
name = "mqtt-client"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-io-async = "0.7.0"
heapless = {path="../../submodules/heapless"}
strum = {version="0.27.2",features=["derive"],default-features = false}
arena = {path="../arena"}
embassy-sync = {path="../../submodules/embassy/embassy-sync"}
embassy-futures = {path="../../submodules/embassy/embassy-futures"}
webpki-roots = "1.0.4"
mqtt-core = {path="../mqtt-core"}
log = "0.4.29"

[dev-dependencies]
tokio-rustls = {version="0.26.4"}
tokio = {version="1.48.0",features=["macros","rt","net","io-util","time"]}
io-adapters = {path="../io-adapters"}