[package]
name = "setup"
version = "0.1.0"
edition = "2024"

[dependencies]
proto = {path = "../../common/proto",features = ["serde"]}
nusb = {version="0.2.1",features = ["tokio"]}
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros", "io-util", "fs", "io-std"] }
clap = { version = "4.5.53", features = ["derive"] }
itertools = "0.14.0"
serde = "1.0.228"
serde-json-core = {path="../../submodules/serde-json-core"}
jsonformat="2.1.0"
