[package]
edition = "2024"
name = "controller"
version = "0.1.0"
license = "MIT OR Apache-2.0"
build = "build.rs"

[dependencies]

embassy-rp = { path = "../../submodules/embassy/embassy-rp", features =["rp235xa","time-driver"]}
embassy-time = { path = "../../submodules/embassy/embassy-time", features = []}
embassy-usb = { path = "../../submodules/embassy/embassy-usb" }
embassy-net = { path = "../../submodules/embassy/embassy-net", features = [ "tcp", "udp", "raw", "dhcpv4", "medium-ethernet", "dns", "proto-ipv4", "proto-ipv6"] }
embassy-futures = { path = "../../submodules/embassy/embassy-futures" }
embassy-executor = { path = "../../submodules/embassy/embassy-executor", features = [ "arch-cortex-m", "executor-thread","executor-interrupt"] }
embassy-sync = { path = "../../submodules/embassy/embassy-sync", features = [] }
cyw43={path = "../../submodules/embassy/cyw43",features = ["bluetooth"]}
cyw43-pio={path = "../../submodules/embassy/cyw43-pio"}
trouble-host = { path= "../../submodules/trouble/host" }

cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = {version="0.7.5",features = []}
log="0.4.28"
cyw43-firmware = { version = "0.1.0", features = ["wifi", "bluetooth"] }
static_cell = {version="2.1.1",features=["nightly"]}
serde = { version = "1.0.228", features = ["derive"],default-features = false }
serde-json-core = "0.6.0"
rand_core = "0.9.3"
uuid={version = "1.18.1",default-features = false}
heapless = {version="0.9.2",features = ["serde"]}
#rust-mqtt = {path="../submodules/rust-mqtt", default-features = false}
embedded-tls = {version="0.17.0",default-features = false}
embedded-hal = "1.0.0"
unicode-segmentation = {version = "1.12.0",default-features = false}
letters = {path="../../common/letters"}
#unidecode = {path="../submodules/rust-unidecode", default-features = false}
#unicode-normalization = {path="../submodules/unicode-normalization", default-features = false}
smoltcp = {version="0.12.0",default-features = false}
embedded-io-async = "0.6.1"
embedded-io = "0.6.1"
mqtt = {path="../../common/mqtt"}
arena = {path="../../common/arena"}
proto = {path="../../common/proto"}

[build-dependencies]
built = {version = "0.8.0", features = ["git2"]}


