[package]
name = "web-client"
version = "0.1.0"
authors = ["Nathan Dobson <nadobson@mac.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.106"
mqtt-client = { path = "../common/mqtt-client" }
console_error_panic_hook = { version = "0.1.7" }
web-sys = { version = "0.3.83", features = [
  "console",
  "Window",
  "Location",
  "UrlSearchParams",
  "HtmlBodyElement",
  "Document",
  "HtmlFormElement",
  "HtmlInputElement",
  "HtmlDivElement",
  "CssStyleDeclaration",
  "HtmlTextAreaElement",
  "Text",
  "HtmlButtonElement",
  "HtmlAnchorElement",
  "HtmlUListElement",
  "HtmlLiElement",
  "HtmlLabelElement",
] }
js-sys = "0.3.83"
wasm-logger = "0.2.0"
log = "0.4.29"
wasm-bindgen-futures = "0.4.56"
url = "2.5.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_qs = "0.15.0"
ws_stream_wasm = { version = "0.7.5", features = ["tokio_io"] }
io-adapters = { path = "../common/io-adapters" }
embassy-futures = "0.1.2"
arena = { path = "../common/arena" }
protocol = { path = "../common/protocol", features = ["serde"] }
tokio = { version = "1.48.0", features = ["sync", "macros"] }
serde-json-core = "0.6.0"
heapless = "0.9.2"
mqtt-core = { path = "../common/mqtt-core" }
uuid = { version = "1.19.0", features = ["v4", "js"] }
futures-util = "0.3.31"
by_address = "1.2.1"
unicode-segmentation = "1.13.2"

[dev-dependencies]
wasm-bindgen-test = "0.3.56"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
