[package]
name = "radio-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
cyw43 = {path="../../submodules/embassy/cyw43"}
cyw43-pio = {path="../../submodules/embassy/cyw43-pio"}
embassy-executor = {path="../../submodules/embassy/embassy-executor"}
embassy-rp = {path="../../submodules/embassy/embassy-rp"}
embassy-sync = {path="../../submodules/embassy/embassy-sync"}
fixed = {version="1.31.0",optional = true}
log = "0.4.29"
make-static = {path="../../common/make-static"}
heapless = {path="../../submodules/heapless",optional = true}
trouble-host = {path="../../submodules/trouble/host",optional = true}
static_cell = "2.1.1"
thiserror={version = "2.0.18",default-features = false}
embassy-net ={path="../../submodules/embassy/embassy-net", optional = true}
embassy-time = {path="../../submodules/embassy/embassy-time", optional=true}
protocol-wifi = {path="../../common/protocol-wifi",optional=true}
embedded-hal-async = "1.0.0"
protocol-ble = {path="../../common/protocol-ble",optional=true,features = ["trouble-host"]}
fixed-freelist = {path="../../common/fixed-freelist",optional = true}
bt-hci = {path="../../submodules/bt-hci"}
serde = {version="1.0.228",optional  = true,default-features = false}
serde-json-core = {path="../../submodules/serde-json-core",optional = true}
embassy-futures = {path="../../submodules/embassy/embassy-futures", optional = true}
error-report = {path="../../common/error-report"}

[features]
default = []
wifi = ["dep:embassy-net","dep:embassy-time","dep:protocol-wifi"]
ble = ["dep:fixed","dep:heapless","dep:trouble-host","dep:protocol-ble","dep:fixed-freelist","dep:serde","dep:serde-json-core","dep:embassy-futures"]
led = []