[package]
name = "setup-client"
version = "0.1.0"
edition = "2024"

[dependencies]
protocol = {path = "../../common/protocol",features = ["serde"]}
nusb = {version="0.2.1",features = ["tokio"]}
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros", "io-util", "fs", "io-std","time"] }
clap = { version = "4.5.53", features = ["derive"] }
itertools = "0.14.0"
serde = "1.0.228"
serde-json-core = {path="../../submodules/serde-json-core"}
jsonformat="2.1.0"
futures-core = "0.3.31"
futures-util = "0.3.31"
btleplug = "0.11.8"
uuid = "1.19.0"

[target.'cfg(darwin)'.dependencies]
objc2={version="0.6.1",features=["disable-encoding-assertions"]}