[workspace]
members = ["board-info","firmware", "radio-builder", "reboot", "runtime", "tls-builder", "usb-builder"]
resolver = "3"

[profile.release]
opt-level = "z"
lto = true
strip = true

[profile.debug-release]
lto = false
inherits = "release"
strip = false
opt-level = "z"
debug = true

[patch.crates-io]
#der = {path="../submodules/formats/der"}