[workspace]
members = ["firmware"]
resolver = "3"

[profile.release]
opt-level = "z"
lto = true
strip = true

[profile.debug-release]
lto = false
inherits = "release"
strip = false
opt-level = "z"
debug = true

[patch.crates-io]
embassy-time = { path = "../submodules/embassy/embassy-time" }
embassy-sync = { path = "../submodules/embassy/embassy-sync" }
embassy-futures = {path ="../submodules/embassy/embassy-futures"}
cyw43 = {path="../submodules/embassy/cyw43"}
heapless = {path="../submodules/heapless"}
ring = {path="../submodules/ring"}