[package]
name = "models"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "inner"
path = "src/inner.rs"

[[bin]]
name = "outer"
path = "src/outer.rs"

[[bin]]
name = "housing"
path = "src/housing.rs"

[[bin]]
name = "flaps"
path = "src/flaps.rs"

[dependencies]
patina-geo={path="../submodules/patina-rs/patina-geo"}
patina-mesh ={path="../submodules/patina-rs/patina-mesh"}
patina-vec={path="../submodules/patina-rs/patina-vec"}
tokio = {version="1.46.1",features=["rt","macros","rt-multi-thread"]}
anyhow = "1.0.98"
patina-sdf= {path="../submodules/patina-rs/patina-sdf"}
patina-threads={path="../submodules/patina-rs/patina-threads"}
itertools = "0.14.0"
patina-bambu = {path="../submodules/patina-rs/patina-bambu"}
patina-extrude = {path="../submodules/patina-rs/patina-extrude"}
patina-font = {path="../submodules/patina-rs/patina-font"}
patina-3mf = {path="../submodules/patina-rs/patina-3mf"}
letters = {path="../common/letters"}

rusttype = "0.9.3"
zip = "4.3.0"
rand = "0.9.2"